INSERT INTO role (name)
SELECT 'SUPER_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'SUPER_ADMIN');

INSERT INTO role (name)
SELECT 'EVENT_MANAGER'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'EVENT_MANAGER');

INSERT INTO role (name)
SELECT 'STAFF'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'STAFF');

INSERT INTO role (name)
SELECT 'ATTENDEE'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ATTENDEE');

INSERT INTO role (name)
SELECT 'VENDOR'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'VENDOR');
