-- DROP SEQUENCE public.app_user_id_seq;

CREATE SEQUENCE public.app_user_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.event_id_seq;

CREATE SEQUENCE public.event_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.role_id_seq;

CREATE SEQUENCE public.role_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tenant_id_seq;

CREATE SEQUENCE public.tenant_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.ticket_id_seq;

CREATE SEQUENCE public.ticket_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.vendor_booth_id_seq;

CREATE SEQUENCE public.vendor_booth_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.databasechangelog definition

-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE public."role" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT role_pkey PRIMARY KEY (id)
);


-- public.tenant definition

-- Drop table

-- DROP TABLE public.tenant;

CREATE TABLE public.tenant (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT tenant_pkey PRIMARY KEY (id)
);


-- public.app_user definition

-- Drop table

-- DROP TABLE public.app_user;

CREATE TABLE public.app_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	email varchar(255) NULL,
	password_hash varchar(255) NULL,
	username varchar(255) NULL,
	tenant_id int8,
	CONSTRAINT app_user_pkey PRIMARY KEY (id),
	CONSTRAINT fksr53t6kfhi9d1k42hv4nlfkkd FOREIGN KEY (tenant_id) REFERENCES public.tenant(id)
);


-- public."event" definition

-- Drop table

-- DROP TABLE public."event";

CREATE TABLE public."event" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	end_date timestamp(6) NULL,
	"location" varchar(255) NULL,
	"name" varchar(255) NULL,
	start_date timestamp(6) NULL,
	created_by int8 NULL,
	tenant_id int8 NOT NULL,
	CONSTRAINT event_pkey PRIMARY KEY (id),
	CONSTRAINT fk2udexp1qqu0v3n03qyty14cmy FOREIGN KEY (tenant_id) REFERENCES public.tenant(id),
	CONSTRAINT fkf6i6epfek19gp3nwd8p4lp3jx FOREIGN KEY (created_by) REFERENCES public.app_user(id)
);


-- public.ticket definition

-- Drop table

-- DROP TABLE public.ticket;

CREATE TABLE public.ticket (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	qr_code varchar(255) NULL,
	seat_number varchar(255) NULL,
	attendee_id int8 NOT NULL,
	event_id int8 NOT NULL,
	CONSTRAINT ticket_pkey PRIMARY KEY (id),
	CONSTRAINT fkfytuhjopeamxbt1cpudy92x5n FOREIGN KEY (event_id) REFERENCES public."event"(id),
	CONSTRAINT fkss7g0v3enr92oli0n4x91sinm FOREIGN KEY (attendee_id) REFERENCES public.app_user(id)
);


-- public.user_role definition

-- Drop table

-- DROP TABLE public.user_role;

CREATE TABLE public.user_role (
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id),
	CONSTRAINT fka68196081fvovjhkek5m97n3y FOREIGN KEY (role_id) REFERENCES public."role"(id),
	CONSTRAINT fkg7fr1r7o0fkk41nfhnjdyqn7b FOREIGN KEY (user_id) REFERENCES public.app_user(id)
);


-- public.vendor_booth definition

-- Drop table

-- DROP TABLE public.vendor_booth;

CREATE TABLE public.vendor_booth (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	booth_name varchar(255) NULL,
	created_at timestamp(6) NULL,
	"location" varchar(255) NULL,
	event_id int8 NOT NULL,
	vendor_id int8 NOT NULL,
	CONSTRAINT vendor_booth_pkey PRIMARY KEY (id),
	CONSTRAINT fkhvwlx9r5q0lm423sxin5mucgr FOREIGN KEY (vendor_id) REFERENCES public.app_user(id),
	CONSTRAINT fkkut1x5ax34s16ucq7glc0rct8 FOREIGN KEY (event_id) REFERENCES public."event"(id)
);